site: Blue State Digital
permalink: /:title.html
exclude: ['node_modules', 'scss', 'package.json', 'Gruntfile.js']
navigation:
- text: Home
  url: ./index.html
- text: About Us
  url: ./about.html
- text: Our Approach
  url: ./approach.html
- text: Our Work
  url: ./case-study.html
- text: Office Interior
  url: ./office-interior.html
